#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/nycrecords/laptop/master/mac
curl --remote-name https://raw.githubusercontent.com/nycrecords/laptop/master/Brewfile
curl --remote-name https://raw.githubusercontent.com/nycrecords/laptop/master/Brewfile.local
curl --remote-name https://raw.githubusercontent.com/joelbcastillo/dotfiles/master/install.sh

/usr/bin/env bash mac 2>&1 | tee ~/laptop.log
